-- MySQL Script generated by MySQL Workbench
-- 04/19/18 19:31:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`albums` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `ab_name` VARCHAR(45) NULL,
  `ab_numberOfSongs` INT NULL,
  PRIMARY KEY (`id_album`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_name` VARCHAR(100) NULL,
  `image_url` VARCHAR(500) NULL,
  `id_image` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artists` (
  `artist_name` VARCHAR(45) NULL,
  `artist_description` VARCHAR(1500) NULL,
  `id_artist` INT NOT NULL AUTO_INCREMENT,
  `id_image` INT NOT NULL,
  PRIMARY KEY (`id_artist`, `id_image`),
  INDEX `fk_artists_images1_idx` (`id_image` ASC),
  CONSTRAINT `fk_artists_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album_detail` (
  `id_album_detail` INT NOT NULL AUTO_INCREMENT,
  `id_album` INT NOT NULL,
  `id_image` INT NOT NULL,
  `id_artist` INT NOT NULL,
  PRIMARY KEY (`id_album_detail`, `id_album`, `id_image`, `id_artist`),
  INDEX `fk_album_detail_albums1_idx` (`id_album` ASC),
  INDEX `fk_album_detail_images1_idx` (`id_image` ASC),
  INDEX `fk_album_detail_artists1_idx` (`id_artist` ASC),
  CONSTRAINT `fk_album_detail_albums1`
    FOREIGN KEY (`id_album`)
    REFERENCES `mydb`.`albums` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_detail_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_detail_artists1`
    FOREIGN KEY (`id_artist`)
    REFERENCES `mydb`.`artists` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genre_name` VARCHAR(45) NULL,
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `genre_description` VARCHAR(250) NULL,
  `id_image` INT NOT NULL,
  PRIMARY KEY (`id_genre`, `id_image`),
  INDEX `fk_genres_images1_idx` (`id_image` ASC),
  CONSTRAINT `fk_genres_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorite_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorite_songs` (
  `id_favorite_songs` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_favorite_songs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`songs` (
  `song_url` VARCHAR(500) NULL,
  `song_name` VARCHAR(45) NULL,
  `id_song` INT NOT NULL AUTO_INCREMENT,
  `id_album_detail` INT NULL,
  `id_image` INT NOT NULL,
  `id_genre` INT NOT NULL,
  `id_artist` INT NOT NULL,
  `id_favorite_song` INT NULL,
  PRIMARY KEY (`id_song`, `id_album_detail`, `id_image`, `id_genre`, `id_artist`, `id_favorite_song`),
  INDEX `fk_songs_album_detail1_idx` (`id_album_detail` ASC),
  INDEX `fk_songs_images1_idx` (`id_image` ASC),
  INDEX `fk_songs_genres1_idx` (`id_genre` ASC),
  INDEX `fk_songs_artists1_idx` (`id_artist` ASC),
  INDEX `fk_songs_favorite_songs1_idx` (`id_favorite_song` ASC),
  CONSTRAINT `fk_songs_album_detail1`
    FOREIGN KEY (`id_album_detail`)
    REFERENCES `mydb`.`album_detail` (`id_album_detail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_genres1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `mydb`.`genres` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_artists1`
    FOREIGN KEY (`id_artist`)
    REFERENCES `mydb`.`artists` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_favorite_songs1`
    FOREIGN KEY (`id_favorite_song`)
    REFERENCES `mydb`.`favorite_songs` (`id_favorite_songs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(15) NULL,
  `status` VARCHAR(20) NULL,
  `token` VARCHAR(700) NULL,
  `display_name` VARCHAR(45) NULL,
  `id_image` INT NULL,
  PRIMARY KEY (`id_user`, `id_image`),
  INDEX `fk_users_images1_idx` (`id_image` ASC),
  CONSTRAINT `fk_users_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlists` (
  `playlist_name` VARCHAR(45) NULL,
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `id_image` INT NOT NULL,
  `playlist_description` VARCHAR(500) NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id_playlist`, `id_image`, `id_user`),
  INDEX `fk_playlists_images1_idx` (`id_image` ASC),
  INDEX `fk_playlists_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_playlists_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `mydb`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlists_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists_has_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlists_has_songs` (
  `id_song` INT NOT NULL,
  `id_playlist` INT NOT NULL,
  INDEX `fk_songs_has_playlists_playlists1_idx` (`id_playlist` ASC),
  INDEX `fk_songs_has_playlists_songs1_idx` (`id_song` ASC),
  PRIMARY KEY (`id_song`, `id_playlist`),
  CONSTRAINT `fk_songs_has_playlists_songs1`
    FOREIGN KEY (`id_song`)
    REFERENCES `mydb`.`songs` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_has_playlists_playlists1`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `mydb`.`playlists` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(50) NULL,
  `time` DATETIME NULL,
  `id_user` INT NOT NULL,
  `id_song` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `id_user`, `id_song`),
  INDEX `fk_comments_users1_idx` (`id_user` ASC),
  INDEX `fk_comments_songs1_idx` (`id_song` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_songs1`
    FOREIGN KEY (`id_song`)
    REFERENCES `mydb`.`songs` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
